sudo: true
language: node_js
node_js:
  - "0.10"
before_install:
  - "npm install npm@2.1.x -g"
before_deploy: npm install -g cf-blue-green
env:
  global:
    - CF_APP=openopps
    - CF_API=https://api.cloud.gov
    - CF_USERNAME=deploy-open-opportunities
    - CF_ORGANIZATION=open-opportunities
    - secure: "Zc1gYl0cfuZsVsxB5RY0oFWmqlELgefOUmj8vLZHubB0OIOYmZ6UNanXgITVwdSNOyKhK7Kizh2C7fsJVMVh2m1YeJjlyU5BF+LjcxV2lmklW56vQ/Gf0zbDt9tvPE+txWGvduFBIGYEOKio1qKSgR6gpYIoFA4irmXOo90x86s="
deploy:
  - provider: script
    script: export CF_SPACE=prod && cf-blue-green-travis
    on:
      branch: master
  - provider: script
    script: export CF_SPACE=staging && cf-blue-green-travis
    on:
      branch: staging
  - provider: script
    script: export CF_SPACE=dev && cf-blue-green-travis
    on:
      branch: dev
